# Numpy Basics Exercises

Please complete the following exercises **using numpy only**.

# Array Broadcasting
NumPy arrays of different dimensionality can be combined in the same expression. Arrays with smaller dimension are broadcasted to match the larger arrays, without copying data.

Broadcasting has two rules.

RULE 1: PREPEND ONES TO SMALLER ARRAY'S SHAPE

RULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING

In [2]:
import numpy as np


In [3]:
a = np.arange(15).reshape(3, 5)
print(a)


b = np.array([1, 2, 3, 4, 5])
print("\n",b,"\n")

result = a + b
print(result)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

 [1 2 3 4 5] 

[[ 1  3  5  7  9]
 [ 6  8 10 12 14]
 [11 13 15 17 19]]


1.Use reduce() operation on an array to reduec it into a single meaningful value. You. can also use a specific axis to apply reduce operation.

2.accumulate() creates a new array containing the intermediate results of the reduce operation at each element in a.


In [4]:
#Reduced
a = np.arange(1, 10).reshape(3, 3)
print(a)
value = np.add.reduce(a)
print("\n",value,"\n")
value_row = np.add.reduce(a,axis=1)
print(value_row,"\n")
value_col = np.add.reduce(a,axis =0)
print(value_col,"\n")
#Acumulate

value = np.add.accumulate(a)
print("\n",value,"\n")
value_row = np.add.accumulate(a,axis=1)
print(value_row,"\n")
value_col = np.add.accumulate(a,axis =0)
print(value_col,"\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [12 15 18] 

[ 6 15 24] 

[12 15 18] 


 [[ 1  2  3]
 [ 5  7  9]
 [12 15 18]] 

[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]] 

[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]] 



### Create a 2-D array where the first row goes from 10 to 80 exclusive with steps of 5 and 2nd row goes from 5 to 47 exclusive with steps of 3

In [5]:
a = np.arange(10,80,5)
print(a,"\n")
b = np.arange(5,47,3)
print(b,"\n")
array = np.vstack((a,b))
print("Required Array : \n",array)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75] 

[ 5  8 11 14 17 20 23 26 29 32 35 38 41 44] 

Required Array : 
 [[10 15 20 25 30 35 40 45 50 55 60 65 70 75]
 [ 5  8 11 14 17 20 23 26 29 32 35 38 41 44]]


### Now use indexing to select the 5th 7th and 11th columns

In [22]:
selected_columns = array[:,[4,6,10]]
print(selected_columns)

[[30 40 60]
 [17 23 35]]


### Select the 2nd row and fourth-last to second-last columns

In [30]:
selected_row = array[1,:]
print(selected_row,"\n")

selected_columns = selected_row[-4:-1] 
print(selected_columns)

[ 5  8 11 14 17 20 23 26 29 32 35 38 41 44] 

[35 38 41]


### Select 3rd to 3rd last columns skipping every second column

In [31]:
selected_columns = array[:,2:-2:2]
print(selected_columns)

[[20 30 40 50 60]
 [11 17 23 29 35]]


###  Select 3rd to 3rd last columns skipping every second column but in reverse order

In [39]:
selected_columns = array[:,2:-2:2]
print(selected_columns)

reversed_columns = selected_columns[:,::-1]

print("\n",reversed_columns)

[[20 30 40 50 60]
 [11 17 23 29 35]]

 [[60 50 40 30 20]
 [35 29 23 17 11]]


### We will work with the following array:

In [60]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Use slicing only to select 3rd and last row along with 2nd and last columns

In [43]:
select = a[[2,-1]][:,[1,-1]]
print(select)

[[11 14]
 [21 24]]


### Extract the following sub-array: [[2, 3], [12, 13], [22, 23]]

In [47]:
sub_array = a[[0,2,4]][:,[2,3]]
print(sub_array)

[[ 2  3]
 [12 13]
 [22 23]]


### Combine fancy/location indexing with slicing to extract the following sub-array: [[6, 8], [16, 18], [21, 23]]

In [53]:
row = [1,3,4]
col = [1,3]

sub_array = a[row][:,[col]]
print(sub_array)

[[[ 6  8]]

 [[16 18]]

 [[21 23]]]


### Change the values 1, 10, 19 and 22 in the array to -2

In [56]:
values= [1,10,19,22]
new_change = -2 
a[np.isin(a,values)]=new_change
print(a)

[[ 0 -2  2  3  4]
 [ 5  6  7  8  9]
 [-2 11 12 13 14]
 [15 16 17 18 -2]
 [20 21 -2 23 24]]


### Repeat above using boolean indexing

In [57]:
values= [1,10,19,22]
new_change = -2 
mask = np.isin(a,values)
a[mask]=new_change
print(a)

[[ 0 -2  2  3  4]
 [ 5  6  7  8  9]
 [-2 11 12 13 14]
 [15 16 17 18 -2]
 [20 21 -2 23 24]]


### Combine slicing in the column dimension and boolean indexing in row dimension to extract the following sub-array: [[0, 3], [10, 13], [15, 18]]

In [61]:
row = [0, 2, 3]
col = [0, 3]
sub_array = a[row][:, col]
print(sub_array)

[[ 0  3]
 [10 13]
 [15 18]]


### Calculating the sum, min and max of all diagonal values

In [62]:
diagonal_values = np.diag(a)
print( diagonal_values)

sum_diagonal = np.sum(diagonal_values)
print("\nSum :", sum_diagonal)

min_diagonal = np.min(diagonal_values)
print("\nMin : ", min_diagonal)

max_diagonal = np.max(diagonal_values)
print("\nMax : ", max_diagonal)

[ 0  6 12 18 24]

Sum : 60

Min :  0

Max :  24


### Calculate the sum of differences between the 2nd row and 2nd last column

In [65]:
second_row = a[1, :]
print("2nd Row: \n", second_row)

second_last_column = a[:, -2]
print("\n2nd Last Column: \n", second_last_column)

differences = second_row - second_last_column
print("\nDifferences: \n", differences)

sum_of_differences = np.sum(differences)
print("\nSum of Differences: \n", sum_of_differences)

2nd Row: 
 [5 6 7 8 9]

2nd Last Column: 
 [ 3  8 13 18 23]

Differences: 
 [  2  -2  -6 -10 -14]

Sum of Differences: 
 -30


### Create a new array that is the sum of even rows and odd rows

In [68]:
even_rows = a[::2, :]
odd_rows = a[1::2, :]
sum_even_rows = np.sum(even_rows, axis=0)
sum_odd_rows = np.sum(odd_rows, axis=0)
sum_array = np.array([sum_even_rows, sum_odd_rows])

print("Even Rows Sum: \n", sum_even_rows)
print("\n Odd Rows Sum: \n", sum_odd_rows)
print("\nNew Array: \n",sum_array)

Even Rows Sum: 
 [30 33 36 39 42]

 Odd Rows Sum: 
 [20 22 24 26 28]

New Array: 
 [[30 33 36 39 42]
 [20 22 24 26 28]]


## You are done. Good job!