In [3]:
import numpy as np

# Q1

Statement: Given a 3D NumPy array arr of shape (2, 3, 4), write a code snippet to calculate the sum of all elements in the array.

Sample Input:

In [6]:
a_3d = np.arange(24).reshape(2,3,4)
total_sum = np.sum(a_3d)
print("Sum of all elements in the array: ", total_sum)

Sum of all elements in the array:  276


# Q2

Statement: Write a NumPy code snippet to create a 4D array arr of shape (2, 3, 4, 5) filled with random integers ranging from 0 to 9.

Sample Output:

In [9]:
b = np.random.randint(0,9,(2,3,4,5))
b

array([[[[8, 3, 7, 1, 0],
         [4, 0, 1, 0, 7],
         [6, 8, 1, 7, 2],
         [4, 5, 8, 0, 0]],

        [[4, 0, 2, 5, 3],
         [5, 2, 1, 1, 8],
         [2, 4, 5, 6, 5],
         [1, 5, 0, 6, 3]],

        [[5, 6, 0, 1, 2],
         [5, 6, 2, 7, 6],
         [2, 5, 2, 1, 5],
         [3, 1, 4, 8, 5]]],


       [[[4, 7, 1, 6, 1],
         [5, 3, 5, 0, 8],
         [2, 2, 0, 5, 6],
         [4, 4, 5, 7, 3]],

        [[5, 8, 1, 4, 4],
         [6, 7, 3, 0, 5],
         [7, 4, 8, 1, 6],
         [8, 3, 8, 0, 8]],

        [[8, 3, 7, 0, 0],
         [6, 8, 8, 1, 1],
         [2, 0, 8, 8, 7],
         [3, 0, 0, 0, 3]]]])

# Q3

Statement: Given a 4D NumPy array arr of shape (2, 3, 4, 5), write a code snippet to calculate the mean along the second axis.

Sample Input:

In [10]:
cal = np.mean(b,axis =0 )
print(cal)

[[[6.  5.  4.  3.5 0.5]
  [4.5 1.5 3.  0.  7.5]
  [4.  5.  0.5 6.  4. ]
  [4.  4.5 6.5 3.5 1.5]]

 [[4.5 4.  1.5 4.5 3.5]
  [5.5 4.5 2.  0.5 6.5]
  [4.5 4.  6.5 3.5 5.5]
  [4.5 4.  4.  3.  5.5]]

 [[6.5 4.5 3.5 0.5 1. ]
  [5.5 7.  5.  4.  3.5]
  [2.  2.5 5.  4.5 6. ]
  [3.  0.5 2.  4.  4. ]]]


# Q4

Statement: You have collected data from a temperature sensor placed at different locations over a period of time. The recorded temperatures are stored in a 3D NumPy array temps of shape (7, 24, 60), where the dimensions represent the number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the average temperature for each day.

Sample Input:

In [17]:

temp = np.random.randint(7,25,(7,24,60))
print(temp,"\n")
avg_temp = np.mean(temp,axis=(1,2))
print(avg_temp)


[[[18 15 19 ...  8 18 13]
  [20 12 18 ... 10 17  8]
  [12 19 24 ... 18 11 21]
  ...
  [12 21 16 ... 24 17 20]
  [10 12 18 ...  9 23 14]
  [ 7 18  7 ... 17 15 20]]

 [[20  7  8 ... 11 23  8]
  [ 7  9  9 ... 22 13 24]
  [ 9 24 18 ... 19 24 13]
  ...
  [ 7 19 11 ... 20 12 10]
  [11 15 12 ...  7 17 15]
  [16 12 24 ... 17 18 21]]

 [[11  8 20 ... 21 19  9]
  [ 9 20  8 ... 19 19 24]
  [10 13  7 ... 20 15  8]
  ...
  [17 17 10 ... 14 18 23]
  [11 19  9 ...  9 10 16]
  [18 18 16 ... 19 13 11]]

 ...

 [[ 7 13 17 ... 16 10 23]
  [13 17 22 ... 10 24 19]
  [24 19 21 ... 14 19 17]
  ...
  [20 23 17 ... 22 16 10]
  [23 10 16 ... 11 24 12]
  [ 8 20 14 ...  9 19 11]]

 [[12 12 15 ... 10  9 17]
  [17 20 13 ... 17 22 20]
  [13 15 24 ... 23 21  7]
  ...
  [ 9 14 18 ...  8  8 23]
  [16 11 24 ... 18 11 24]
  [13 23 17 ... 17 19 23]]

 [[22  7 16 ...  8 21 22]
  [23 17 14 ...  7  8 11]
  [17 18 12 ... 19 12 15]
  ...
  [ 9 21 19 ...  9 17 16]
  [14 15 23 ... 11  9 24]
  [10 23 16 ... 11 20 23]]] 

[15.6687

Sample Output:

array([27.43864059, 26.99643944, 27.10398301, 27.43854821, 26.81072977,
       26.76581481, 27.07946152])

# Q5

Statement: You have collected data from multiple sensors placed in different rooms of a building. The sensor readings are stored in a 4D NumPy array readings of shape (4, 7, 24, 60), where the dimensions represent the number of sensors, number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the maximum reading for each sensor across all days.

In [18]:
import numpy as np
readings = np.random.rand(4, 7, 24, 60)
max_read = np.max(readings, axis=(1, 2, 3))

print("Maximum readings for each sensor:", max_read)


Maximum readings for each sensor: [0.99993137 0.9999365  0.99963259 0.9999586 ]


# Q6

Statement: You have collected data from a 3D printer that measures the dimensions of printed objects. The recorded dimensions are stored in a 3D NumPy array dimensions of shape (100, 50, 3), where the dimensions represent the number of printed objects, number of measurements for each object, and the three dimensions (length, width, height), respectively. Write a code snippet to calculate the average length, width, and height across all objects.

Sample Inpumt:

In [20]:
arr_dism =np.random.rand(100,50,3)
average_dimensions = np.mean(arr_dism, axis=(0, 1))

print("Average dimensions (length, width, height):", average_dimensions)


Average dimensions (length, width, height): [0.5029743  0.50132233 0.5006288 ]


# Q7

Statement: You are given a 3D NumPy array data of shape (5, 6, 7) representing the sensor readings from multiple sensors placed in different locations over a period of time. Each sensor provides measurements at different time points. Write a code snippet to calculate the following statistics for each sensor:

Total number of measurements

Average measurement value

Standard deviation of measurements

Minimum measurement value

Maximum measurement value

Sample Input:

In [21]:
data = np.random.rand(5, 6, 7)
total_measurements = data.shape[1] * data.shape[2]
average_measurement = np.mean(data, axis=(1, 2))
std_deviation = np.std(data, axis=(1, 2))
min_measurement = np.min(data, axis=(1, 2))
max_measurement = np.max(data, axis=(1, 2))

print("Total number of measurements for each sensor:", total_measurements)
print("Average measurement value for each sensor:", average_measurement)
print("Standard deviation of measurements for each sensor:", std_deviation)
print("Minimum measurement value for each sensor:", min_measurement)
print("Maximum measurement value for each sensor:", max_measurement)



Total number of measurements for each sensor: 42
Average measurement value for each sensor: [0.53221842 0.56350146 0.55924706 0.4984795  0.50814282]
Standard deviation of measurements for each sensor: [0.28633427 0.28411036 0.27391977 0.31115732 0.29163058]
Minimum measurement value for each sensor: [0.0514297  0.06430669 0.07978697 0.02686596 0.0117299 ]
Maximum measurement value for each sensor: [0.99636428 0.99754963 0.9802541  0.98676943 0.99717048]
