In [1]:
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Q.1
**Statement:** You are working with a retail store that needs to manage its inventory efficiently. They have provided you with a dataset containing information about products, their quantities in stock, and the number of units sold daily for the past week. Total number of products are 5. Your task is to calculate the following:



1.The total sales for each product over the past week.

2.The average daily sales for each product.

3.The product with the highest sales.

4.The product with the lowest sales.

5.The total sales for all products combined.

You are required to use NumPy for efficient data processing and calculations. Write code to solve this inventory management problem.

In [1]:
import numpy as np
product_names = np.array(['Product A', 'Product B', 'Product C', 'Product D', 'Product E', 'Product F','Product G'])
quantities_in_stock = np.array([100, 150, 200, 250, 50])
daily_sales_data = np.array([[10, 15, 20, 25, 30, 35, 40],
                             [5, 7, 8, 10, 12, 14, 16],
                             [15, 20, 25, 30, 35, 40, 40],
                             [12, 25, 20, 40, 20, 32, 55],
                             [15, 20, 25, 30, 35, 40, 45]])
total_sales_revenue = np.dot(quantities_in_stock, daily_sales_data)
average_daily_sales = np.mean(daily_sales_data, axis=1)
highest_sales_product = product_names[np.argmax(total_sales_revenue)]
lowest_sales_product = product_names[np.argmin(total_sales_revenue)]
total_sales_revenue_all_products = np.sum(total_sales_revenue)
print("Total Sales for Each Product:\n", total_sales_revenue)
print("Average Daily Sales for Each Product:\n", average_daily_sales)
print("Product with Highest Sales:", highest_sales_product)
print("Product with Lowest Sales:", lowest_sales_product)
print("Total Sales Revenue for All Products:", total_sales_revenue_all_products)


Total Sales for Each Product:
 [ 8500 13800 14450 21500 18550 23600 30400]
Average Daily Sales for Each Product:
 [25.         10.28571429 29.28571429 29.14285714 30.        ]
Product with Highest Sales: Product G
Product with Lowest Sales: Product A
Total Sales Revenue for All Products: 130800


# Q.2
**Statement:** Statement: You are working with a manufacturing plant that produces various components. They have provided you with data on the production rates of five different machines over the past month. Your task is to analyze the performance of these machines by calculating the following metrics:

1.The total production output for each machine over the past month.

2.The average daily production rate for each machine.

3.The machine with the highest total production output.

4.The machine with the lowest total production output.

The overall production efficiency of the plant, which is defined as the ratio of the total production output to the total number of hours worked, and working hour for each day is 2 hours.

In [2]:

production_rates = np.random.randint(100, 200,(5, 30))
total_production_output = np.sum(production_rates, axis=0)

average_daily_production = np.mean(production_rates, axis=1)

highest_production_output_machine = np.argmax(total_production_output)
lowest_production_output_machine = np.argmin(total_production_output)

overall_production_efficiency = np.sum(total_production_output) / (2 * 30)

print("Total Production Output for Each Machine:\n", total_production_output)
print("\nAverage Daily Production Rate for Each Machine:\n", average_daily_production)
print("\nMachine with Highest Total Production Output:", highest_production_output_machine)
print("Machine with Lowest Total Production Output:", lowest_production_output_machine)
print("Overall Production Efficiency of the Plant:", overall_production_efficiency)


Total Production Output for Each Machine:
 [856 795 755 695 624 792 737 814 805 767 714 699 739 850 754 856 657 744
 727 729 866 778 780 765 695 822 814 772 687 814]

Average Daily Production Rate for Each Machine:
 [156.53333333 152.86666667 152.66666667 155.76666667 145.56666667]

Machine with Highest Total Production Output: 20
Machine with Lowest Total Production Output: 4
Overall Production Efficiency of the Plant: 381.7


# Q3:

**Statment**
You are working on a project that involves simulating sensor data for a network of 10 sensors over a period of 15 days. Each sensor collects data once per hour. Your task is to generate a NumPy array named sensor_data to represent this simulated sensor data and perform following statistical analysis on it.

Populate the sensor_data array with random floating-point values between 0.0 and 100.0
The generated values should represent sensor readings collected once per hour.

After generating the sensor_data array, perform the following statistical **calculations:**

1.Calculate the mean (average) sensor reading for each sensor over the 15 days.

2.Calculate the standard deviation of sensor readings for each sensor.

3.Calculate the maximum sensor reading for each sensor.

4.Calculate the minimum sensor reading for each sensor.

5.Calculate the overall mean sensor reading for all sensors and all days.

6.Calculate the overall standard deviation of sensor readings for all sensors an

In [3]:
import numpy as np

num_sensors = 10
num_days = 15
hours_per_day = 24
shape = (num_sensors, num_days * hours_per_day)

sensor_data = np.random.uniform(0.0, 100.0, size=(num_sensors, num_days))

print("Sensor Data:\n", sensor_data)

mean_sensor_reading = np.mean(sensor_data, axis=0)
print("\n1. Mean Sensor Reading for Each Sensor:\n", mean_sensor_reading)

std_sensor_reading = np.std(sensor_data, axis=0)
print("\n2. Standard Deviation of Sensor Readings for Each Sensor:\n", std_sensor_reading)

max_sensor_reading = np.max(sensor_data, axis=0)
print("\n3. Maximum Sensor Reading for Each Sensor:\n", max_sensor_reading)

min_sensor_reading = np.min(sensor_data, axis=0)
print("\n4. Minimum Sensor Reading for Each Sensor:\n", min_sensor_reading)

overall_mean_sensor_reading = np.mean(sensor_data)
print("\n5. Overall Mean Sensor Reading for All Sensors and All Days:", overall_mean_sensor_reading)

overall_std_sensor_reading = np.std(sensor_data)
print("\n6. Overall Standard Deviation of Sensor Readings for All Sensors and All Days:", overall_std_sensor_reading)



Sensor Data:
 [[1.36125488e+01 3.86097772e+01 5.89376563e+01 9.35887280e+00
  5.36309992e+01 3.78879091e+00 8.87750770e+01 5.30436993e+01
  5.77631026e+01 2.56116145e+01 3.20202760e+01 2.29402330e+01
  6.76014373e+01 9.25822348e+01 3.33252026e+01]
 [9.63266057e+01 3.35645407e+01 7.55568056e+01 4.29012323e+01
  7.01787684e+00 4.34866264e+00 1.40504216e+01 6.92689402e+01
  9.49912259e+01 2.52339612e+01 2.13169855e+01 4.08653251e-02
  7.99780707e+01 3.63667178e+01 2.76146329e+01]
 [1.67616234e+01 5.15031603e+01 9.37073429e+01 4.26900878e+01
  4.50130919e+00 6.29792538e+01 1.58521306e+01 8.54122897e+01
  5.06209947e+01 2.07306645e+01 3.46269103e+01 7.64274465e+01
  7.33084451e+01 1.05238278e+01 8.05550575e+01]
 [5.95937885e+01 7.61990989e+01 3.68301901e+01 5.26189873e+01
  8.85088885e+01 6.38805189e+01 8.96455714e+01 6.82273701e+01
  1.05207744e+01 7.01764089e+01 6.25827391e+01 5.37073132e+01
  3.03575782e+01 1.97455892e+01 7.52326188e+01]
 [1.99309100e+01 1.65473857e+01 8.97366810e+00 5.5

# Q4:

**Statement**: You are tasked with analyzing the exam scores of 30 students in a class over a period of 10 exams. The exam scores are represented as a NumPy, where each row corresponds to a different student, and each column represents their score in a specific exam.

Populate the exam_scores array with random integer values between 50 and 100 to simulate students' exam performance.

After generating the exam_scores array, perform the following tasks:

1.Calculate the average score for each student over the 10 exams.

2.Calculate the standard deviation of scores for each student.

3.Identify students who have consistently performed well, defined as those whose average score is above 85.

4.Identify students who may need additional support, defined as those whose average score is below 50.

Write code to create and populate the exam_scores array and then perform the specified statistical analysis and performance evaluation tasks on the data.





In [4]:
import numpy as np

num_students = 30
num_exams = 10

exam_scores = np.random.randint(50, 101, size=(num_students, num_exams))

print("Exam Scores:\n", exam_scores)

average_scores = np.mean(exam_scores, axis=1)
print("\n1. Average Score for Each Student:\n", average_scores)

std_scores = np.std(exam_scores, axis=1)
print("\n2. Standard Deviation of Scores for Each Student:\n", std_scores)

consistent_students = exam_scores[average_scores > 85]
print("\n3. Students with Consistent Performance:\n", consistent_students)

support_students = exam_scores[average_scores < 60]
print("\n4. Students with Additional Support Needed:\n", support_students)



Exam Scores:
 [[ 81  93  88  98  60  53  78  81  72  97]
 [ 78 100  92  50  89  50  73  97  61  63]
 [ 87  90  98  58  82  51  67  68  97  88]
 [ 82  87 100  61  96  79  82  65  64  67]
 [ 52  60  78  63  92  77  68  98  74  74]
 [ 97  81  97  60  88  96  50  90  85  56]
 [ 97  51  94  58  52  85  92  71 100  91]
 [ 82  56  86  58  96  65  96  90  75  82]
 [ 72  64  50  50  81  72  89  99  98  91]
 [ 55 100  59  61  64  88  91  59  79  96]
 [ 79  56  52  60  59  74  78  67  88  64]
 [ 94  98  92  90  61  97  97  72  91  95]
 [ 66  68  51  99  63  82  69  97  69  66]
 [ 51  57  74  67  60  66  96  57  86  67]
 [ 95  72  95  88  98  63  55  52  97  50]
 [ 98  82  93  90  57  89  62  74  71  92]
 [ 86  64  67  93  83  94  92  88  61  96]
 [ 53  51  81  81  83  64  79  57  61  85]
 [ 51  65  75  56  80  66  91  53  52  52]
 [ 87  78 100  85  61  79  77  87  96  75]
 [100  64  78  94  56  64  59  73  96  57]
 [ 78  85  81  97  74  84  77  84  76  91]
 [ 74  99  51  66  94  71  58  83  59  9