In [61]:
import numpy as np

# Step 1 : Read the Data!

In [62]:
census = r"C:\Users\Muhammad_Talha\Downloads\COHORT 7\Week 1\Numpy\Numpy Project\makeSenseOfCensus.csv"
census

'C:\\Users\\Muhammad_Talha\\Downloads\\COHORT 7\\Week 1\\Numpy\\Numpy Project\\makeSenseOfCensus.csv'

# Loading the data

You have studied getfromtext in Numpy Classes, now is the time to put it into action :) Below is the half completed code, you have to substitute values for delimiter and skip_header in it for hte data to be properly read into a Data array. The output of the array has been shared with you guys followed by the code block

In [63]:
census_array = np.genfromtxt(census, delimiter = ",", skip_header = 1)
print("\nData:\n\n ", census_array)


Data:

  [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


# Printing the type of data

In [64]:
print(type(census_array))

<class 'numpy.ndarray'>


# Step 2 : Append the Data

A new record [[50,9,4,1,0,0,40,0]] has been given to you. You are supposed to append this new record into the data using np.concatenate()

In [65]:
new_record = [[50,9,4,1,0,0,40,0]]

## Append 'new_record' (given) to 'data' using "np.concatenate()"

In [66]:
new_record_np = np.array(new_record)
census_array = np.concatenate((census_array, new_record_np), axis=0)

In [67]:
#display after appending the new record at the end of the array.
census_arr

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [48., 13.,  4., ...,  0., 58.,  1.],
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.]])

# Step 3 : Check if it's a young country or old country

 Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.

In [68]:
age = census_arr[:, 0]

Find the max age and store it in a variable called 'max_age'.



In [69]:
max_age = np.max(age)
print(max_age)

90.0


Find the min age and store it in a variable called 'min_age'.

In [70]:
min_age = np.min(age)
print(min_age)

17.0


Find the mean of the age and store it in a variable called 'age_mean'.

In [71]:
age_mean = np.mean(age)
print(age_mean)

38.051


Find the standard deviation of the age and store it in a variable called 'age_std'

In [72]:
age_std = np.std(age)
print(age_std)

13.342803266180612


# Step 4: Let's check the country's race distribution to identify the minorities

Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

In [73]:
race_0 = census_arr[census_arr[:, 2] == 0]
race_1 = census_arr[census_arr[:, 2] == 1]
race_2 = census_arr[census_arr[:, 2] == 2]
race_3 = census_arr[census_arr[:, 2] == 3]
race_4 = census_arr[census_arr[:, 2] == 4]

In [74]:
len_0 = len(race_0)
len_1 = len(race_1)
len_2 = len(race_2)
len_3 = len(race_3)
len_4 = len(race_4)

Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

In [75]:
len_0

10

In [76]:
len_1

27

In [77]:
len_2

110

In [78]:
len_3

6

In [79]:
len_4

847

Find out which is the race with the minimum no. of citizens

In [80]:
length = [
    ('Race 0', len_0),
    ('Race 1', len_1),
    ('Race 2', len_2),
    ('Race 3', len_3),
    ('Race 4', len_4)
]
min_citizens = min(length, key=lambda x: x[1])
min_citizens

('Race 3', 6)

Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [81]:
minority_race_index = length.index(min(length, key=lambda x: x[1]))
minority_race_index

3

# Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

a.Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)

[Row,Columns]  :

In [82]:
senior_citizens = census_arr[census_arr[:, 0] > 60]
senior_citizens

array([[7.9000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.7000e+01, 6.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+00, 0.0000e+00],
       [7.6000e+01, 1.4000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 1.0000e+00],
       [6.1000e+01, 9.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [7.0000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [6.4000e+01, 7.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        2.1790e+03, 4.0000e+01, 0.0000e+00],
       [7.1000e+01, 1.0000e+01, 2.0000e+00, 1.0000e+00, 0.0000e+00,
        1.8160e+03, 2.0000e+00, 0.0000e+00],
       [6.8000e+01, 2.0000e+00, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.6000e+01, 1.1000e+01, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+

b.Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'

In [83]:
w_h_sum = np.sum(senior_citizens[:, 6])
w_h_sum

1917.0

c.Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'

In [84]:
senior_citizens_len = len(senior_citizens)
senior_citizens_len

61

d. Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.

In [85]:
avg_working_hours =  w_h_sum/senior_citizens_len

e. Print 'avg_working_hours' and see if the govt. policy is followed.

In [86]:
# As per govt. records citizens above 60 should not work more than 25 hours a
if (avg_working_hours < 25):
  print("Policy is followed", avg_working_hours)
else:
  print("Policy not followed as working hours are =", avg_working_hours)

Policy not followed as working hours are = 31.42622950819672


# Step 6: Let's check that higher educated people have better pay in general.

Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.



In [87]:
high = census_arr[census_arr[:, 0] > 10]
low = census_arr[census_arr[:, 0] <= 10]

Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.

In [88]:
if high.size != 0 :
    avg_pay_high = np.mean(high[:, 7])
else:
    avg_pay_high = 0

print("Average pay for high education:", avg_pay_high)

Average pay for high education: 0.232


In [90]:
if low.size > 0:
    avg_pay_low = np.mean(low[:, 7])
else:
    avg_pay_low = 0

print("Average pay for low education:", avg_pay_low)

Average pay for low education: 0
